name: full_responsive
description: The ultimate solution for running your Flutter App in every screen size/resolution/ratio through the easiest/leanest design-development workflow possible.
version: 0.0.1
repository: https://github.com/Rodsevich/full_responsive
homepage: https://gitlab.com/Rodsevich/full_responsive

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
